### ISSUE TITLE
Tweak for iOS8 beta 4

### ISSUE THREAD

**Issue by briangershon** [x43x61x69/Swift-UUID#1]
I'm using a snippet of your code in my project.

For latest beta I had to make this change:

from:

```
uuid = CFBridgingRelease(uuidStringRef!) as String
```

to:

```
uuid = uuidStringRef! as NSString
```

https://github.com/x43x61x69/Swift-UUID/blob/master/src/Swift%20UUID/AppDelegate.swift#L72

CFBridgingRelease is no longer supported.

**Comment by x43x61x69** [comment]
Hi @briangershon!

Good to know. I haven't have chance to use those snippets in any projects yet, so didn't notice.

And yea, they changed a lot of things in beta 3 and beta 4, which is really a PITA. I'll have a look later and update the code.

---

After playing around, seems there's still bugs in beta 4 and LLVM could point out what's wrong with some part of my code. I won't be able to make `getSystemSerialNumber()` works, so I'll pause the update till they fix LLVM itself.

Cheers!
Cai

**Comment by briangershon** [comment]
Thanks @x43x61x69 for fixing so quickly, and making this code available -- was a great starting place for what I needed.
